<?php

use Icinga\Web\Navigation\ConfigMenu;
use Icinga\Web\Widget\SearchDashboard;

$searchDashboard = new SearchDashboard();
$searchDashboard->setUser($this->Auth()->getUser());

if ($searchDashboard->search('dummy')->getPane('search')->hasDashlets()): ?>
    <form action="<?= $this->href('search') ?>" method="get" role="search" class="search-control">
        <i class="icon fa-search fa search-icon"></i>
        <input type="text" name="q" id="search" class="search search-input" required
               placeholder="<?= $this->translate('Search') ?> (/)&hellip;"
               aria-label="<?= $this->translate('Search') ?> (/)"
               list="search-history-list"
               autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
        <button class="search-reset icon-cancel" type="reset"
                title="<?= $this->translate('Clear search') ?>"
                aria-label="<?= $this->translate('Clear search') ?>"></button>
        <datalist id="search-history-list"></datalist>
    </form>
    <div
        class="search-history-container"
        data-search-history-container
        data-title-label="<?= $this->escape($this->translate('Recent Searches')) ?>"
        hidden
    >
        <p class="search-history-title"></p>
        <div class="search-history-actions"></div>
    </div>
<?php endif; ?>
<?= $menuRenderer->setCssClass('primary-nav')->setElementTag('nav')->setHeading(t('Navigation')); ?>
<nav class="config-menu">
    <?= new ConfigMenu() ?>
</nav>
