<div class="controls">
<?php if (! $this->compact): ?>
<?= $this->tabs ?>
<?php endif ?>
    <div class="sort-controls-container">
        <button
            type="button"
            class="button-link js-toggle-dashlet-view"
            data-label-classic="<?= $this->escape($this->translate('Classic View')) ?>"
            data-label-containers="<?= $this->escape($this->translate('Container View')) ?>"
            data-label-unavailable="<?= $this->escape($this->translate('Container view unavailable in compact layout')) ?>"
            title="<?= $this->escape($this->translate('Classic View')) ?>"
        >
            <?= $this->escape($this->translate('Classic View')) ?>
        </button>
        <button
            type="button"
            class="button-link js-reset-dashlet-layout"
            title="<?= $this->escape($this->translate('Reset dashboard layout to default arrangement')) ?>"
        >
            <?= $this->escape($this->translate('Reset Layout')) ?>
        </button>
    </div>
</div>
<?php if ($this->dashboard): ?>
    <div class="dashboard content floating-dashlets">
    <?= $this->dashboard ?>
    </div>
<?php else: ?>
    <div class="content">
        <h1><?= $this->escape($this->translate('Welcome to Icinga Web!')) ?></h1>
        <p>
        <?php if (! $this->hasPermission('config/modules')) {
            echo $this->escape($this->translate(
                'Currently there is no dashlet available. Please contact the administrator.'
            ));
        } else {
            printf(
                $this->escape($this->translate('Currently there is no dashlet available. This might change once you enabled some of the available %s.')),
                $this->qlink($this->translate('modules'), 'config/modules')
            );
        } ?>
        </p>
    </div>
<?php endif ?>
