<div class="controls">
<?= $this->dashboard->getTabs() ?>
    <div class="sort-controls-container">
        <button
            type="button"
            class="button-link js-reset-dashlet-layout"
            title="<?= $this->escape($this->translate('Reset dashboard layout to default arrangement')) ?>"
        >
            <?= $this->escape($this->translate('Reset Layout')) ?>
        </button>
    </div>
</div>

<div class="content dashboard floating-dashlets">
<?= $this->dashboard ?>
</div>
