name: Guardrails

on:
  push:
    branches:
      - main
      - release/*
      - support/*
  pull_request:
    branches:
      - main

jobs:
  phpstan-baseline-budget:
    name: PHPStan baseline budget
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP and dependencies
        uses: Icinga/github-actions/.github/actions/php-and-dependencies@ea00fefeee718346f7cf319b61e430243c0a3797
        with:
          php-version: '8.2'
          php-tools: composer

      - name: Enforce PHPStan baseline budget
        run: composer run stan:baseline:guard
